### ISSUE TITLE
Copies files that are excluded in config files

### ISSUE THREAD

**Issue by berrberr** [imathis/guard-jekyll-plus#23]
In Jekyll config files you can define an array of files and directories to exclude from the build (ie. after the build they will not be copied to the _site directory). However, when guard is running and one of the files in the Jekyll exclude array is modified that file is still copied into the _site (or whatever) directory.

I would expect nothing (no copying) to happen if I modify a file that is part of the Jekyll exclude settings while running guard.

**Comment by paulrobertlloyd** [comment]
I’m still seeing this issue. When using @berrberr’s fork, files/patterns listed in `exclude:` are excluded as expected (example resulting message: ` ~ 'source/_stylesheets/structure/_page.scss' detected in Jekyll exclude, not building`).

However, when using the latest version of your Gem @imathis (great to see it maintained again BTW!), Jekyll builds are initiated regardless of config. This is puzzling, as you’ve merged @berrberr’s fix; I wonder if this has been updated since his initial PR?

**Comment by paulrobertlloyd** [comment]
Just to confirm, tried the same using the Gem pulled from master, and the same issue is exhibited.

**Comment by paulrobertlloyd** [comment]
Ping @imathis; any ideas what’s happening here?

**Comment by imathis** [comment]
I'm not sure. I'll take a look when I get a chance. Thanks for the Ping!

**Comment by paulrobertlloyd** [comment]
No worries… I don't wish to bother you. Currently juggling between @berrberr’s (which I’ll need to fork for it to work with 3.0), and your original project.
